### ISSUE TITLE
max interpeter pathing bug

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget#21]
## TODO
- [ ] get it to work in max
- [ ] test on another computer with max
- [x] fix "python" hack, replace w max itnerpreter path in plugget max_req action
- [x] ensure plugget or pypip catches the error, instead of silent crash
    - [x] log it to user!

## Problem

it seems max has issues if anyoher python version is installed.
python310 is in the PATH. max 2024 uses 3.9

simply trying to run `"C:\Program Files\Autodesk\3ds Max 2024\Python\python.exe"` in interpreter results in:
```
C:\Users\hanne>"C:\Program Files\Autodesk\3ds Max 2024\Python\python.exe"
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Python310\\lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

---

testcode
```python
import plugget
plugget.uninstall("req-test-dummy")
plugget.install("req-test-dummy")
```

**Comment by hannesdelbeke** [comment]
workaround use "python" instead of interpreter.
but not sure why this works. this now should be same as py_pip

```python
import subprocess

command = ['python', '-m', 'pip', 'install', '-r', 'C:\\Users\\hanne\\AppData\\Local\\Temp\\plugget\\max3ds\\d2181116\\req-test-dummy\\1.0\\req-test-dummy\\requirements.txt', '--upgrade', '--target', 'C:\\Users\\hanne\\AppData\\Roaming\\Python\\Python39\\site-packages', '--no-user']

process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

# Wait for the process to finish
stdout, stderr = process.communicate()

# Print the output
print("Standard Output:")
print(stdout)

print("\nError Output:")
print(stderr)

# Wait for user input before closing the console
input("Press Enter to exit...")
```

**Comment by hannesdelbeke** [comment]
main diff is that for py_pip we pass env along
python 310 is multiple times in the PATH.
but AFAIK running this in cmd has the same result

**Comment by hannesdelbeke** [comment]
bug likely related to path issues
after printing py_pip output i get

```
Traceback (most recent call last):
  File "C:\Program Files\Autodesk\3ds Max 2024\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Autodesk\3ds Max 2024\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_internal\exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pkg_resources\__init__.py", line 35, in <module>
    import plistlib
  File "C:\Program Files\Autodesk\3ds Max 2024\Python\lib\plistlib.py", line 61, in <module>
    from xml.parsers.expat import ParserCreate
  File "C:\Program Files\Autodesk\3ds Max 2024\Python\lib\xml\parsers\expat.py", line 4, in <module>
    from pyexpat import *
ImportError: DLL load failed while importing pyexpat: The specified module could not be found.
```

**Comment by hannesdelbeke** [comment]
wonder if something is bugged w my max install. it still tries to import py310 even when remoived from path.
need to test on another pc

**Comment by hannesdelbeke** [comment]
setup plugget in max
- was done with py310
`pip install -e "C:\Users\hanne\OneDrive\Documents\repos\plugget" --target "C:\Users\hanne\AppData\Roaming\Python\Python39\site-packages"`
wonder if editable install has any traces
